on:
  workflow_dispatch
jobs:
  hello_world_job:
    runs-on: self-hosted
    name: Test
    steps:
      # - uses: actions/checkout@v4
      - uses: jtamaki/adoc2pdf@main
        with:
          input_dir: '.' #'doc'
          output_dir: ${{ runner.temp }}
      - run: ls ${{ runner.temp }}
